### ISSUE TITLE
Error FullyQualifiedErrorId 

### ISSUE THREAD

**Issue by aleex-bro** [jayendranarumugam/PowerBI-CICD#2] opened 2020-05-19 08:08 UTC
Hi Jay,

Thanks a lot for your script. Everything worked fine except updating the data source credentials. I am an using PowerBI Embedded and I am trying to update the data source credentials for a dataset.

The script runs smooth (getting the dataset, the gateway etc.) but on the Updating the credentials, I am running into the following.

"+ Invoke-PowerBIRestMethod -Url "gateways/$($BounGateway.value.gatewayI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...werBIRestMethod:InvokePowerBIRestMethod) [Invoke-PowerBIRestMethod], AggregateException
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod"

Here is my code:

 $UpdateUserCredential = @{ 
            credentialType ="Basic" 
            encryptedConnection = "Encrypted"
            encryptionAlgorithm = "None"
            privacyLevel = "None" 
            credentials = 
            @{             
            username= "saadmin"
            password= "yg4aDxKTmx8AZNRX!"
            }
            
} | ConvertTo-Json

Write-Host ($UpdateUserCredential)

Invoke-PowerBIRestMethod -Url "gateways/$($BounGateway.value.gatewayId)/datasources/$($BounGateway.value.id)" -Method PATCH -Body $UpdateUserCredential | ConvertFrom-Json
 

Any ideas ?

**Comment by jayendranarumugam** [comment] 2020-05-20 03:35
Hi @aleex-bro  , First run the script in your local and use fiddler to find the exact error message . The Powershell error message is not too specific for finding the root cause.

I think something it was failing at at user credentials level (check firewall/ correct password)

Thanks !
Jay

**Comment by jayendranarumugam** [comment] 2020-09-07 12:18
Closing the issue,as not received any further updates. Feel free to re-open or provide your queries.

**Closed as completed by jayendranarumugam** 2020-09-07 12:18 UTC

**Comment by souvik221** [comment] 2022-02-03 12:08
Hi Jay,

I am getting following error while I am trying to execute your script. This is getting failed at the last step Invoke-PowerBIRestMethod. Please help and support.

  + CategoryInfo          : WriteError: (Microsoft.Power...werBIRestMethod:InvokePowerBIRestMethod) [Invoke-PowerBIRestMethod], AggregateException
  + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod"
